apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "fabric-hcs-orderer.labels" . | nindent 4 }}
  name: {{ include "fabric-hcs-orderer.fullname" . }}
type: Opaque
stringData:
  orderer.yaml: |-
    # merge config from file and values
    {{- .Files.Get "orderer.yaml" | nindent 4 }}
    Hcs:
    {{- toYaml .Values.config.hcs | nindent 8 }}
    {{- if eq .Values.config.network "mainnet" -}}
      {{- toYaml .Values.network.mainnet | nindent 8 }}
    {{- else -}}
      {{- toYaml .Values.network.testnet | nindent 8 }}
    {{- end -}}
