apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "fabric-hcs-orderer.labels" . | nindent 4 }}
  name: {{ include "fabric-hcs-orderer.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "fabric-hcs-orderer.selectorLabels" . | nindent 4 }}
